worked on task 6 and added relevant tests, created new comments files…
krahma93/KR-portfolio-news pull request #5
Opened 2022-12-13 16:08 UTC by krahma93

… for controller and model

2022-12-13 16:44 UTC, Dutton1990 commented on __tests__/app.test.js
> +            expect(comments[0]).toEqual(
Instead of just checking the first comment, use a forEach again to loop over and check every single one

2022-12-13 16:46 UTC, Dutton1990 requested changes
There's another test you can add, what if an article exists but has no comments? 

This should return a 200 because it's a correct request, but also return an empty array of comments. 

See if you can add this test and figure out how you could go about this. You might need to check that the article exists 🤔 

Send this PR again please once you've done that. Nice work otherwise!

2022-12-14 09:31 UTC, leekli requested changes
Hi Khaled, thanks for making the changes Christian asked.

There's 1 more request, which looks like you had it before but you took it out?

You need a test and some logic to deal with trying to get comments for an article which does not exist. For example if I went to /api/articles/768787/comments... that article_id does not exist. Have another look at getting this implemented.

Once complete, please submit another pull request to us for review.

2022-12-14 10:44 UTC, leekli approved these changes
Fantastic, well done Khaled!

You are free to merge this branch :D

2022-12-14 10:49 UTC, merged